version: "3.8"
services:
  postgres:
    image: postgres:11
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bill-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db:
    driver: local
