version: '3.8'
services:
  postgres:
    image: postgres:11
    restart: "always"
    expose: 
      - "5432"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=bill-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./db/data:/var/lib/postgresql/data"
      - "./db/init:/docker-entrypoint-initdb.d"
